version: "3.8"
services:
  insurancedb:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=sleshainsurance
    networks:
      - sleshainsnetwork
  reverseproxy:
    container_name: proxy
    image: viggy6/sleshainsurance-reverseproxy
    networks:
      - sleshainsnetwork
  rediscache:
    container_name: cache
    depends_on:
      - insurancedb
    image: viggy6/sleshainsurance-rediscache
    networks:
      - sleshainsnetwork
  userms:
    container_name: userms
    depends_on:
      - insurancedb
    image: viggy6/sleshainsurance-userms
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "userms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    networks:
      - sleshainsnetwork
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sleshainsnetwork
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - sleshainsnetwork
  planms:
    container_name: planms
    depends_on:
      - insurancedb
    image: viggy6/sleshainsurance-planms
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "planms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.cache.type":"redis",
        "spring.redis.host":"rediscache",
        "spring.redis.port":"6379",
        "configs:spring.cache.cache-names":"plan, userPlan"}'
    networks:
      - sleshainsnetwork
  processms:
    container_name: processms
    depends_on:
      - planms
    image: viggy6/sleshainsurance-processms
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "processms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    networks:
      - sleshainsnetwork
  sleshainsuranceui:
    container_name: ui
    depends_on:
        - userms
        - planms
    image: viggy6/sleshainsurance-sleshainsuranceui
    networks:
      - sleshainsnetwork

networks:
  sleshainsnetwork: {}
